# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# This block sets up CocoaPods for Flutter – required
flutter_root = File.expand_path('..', File.dirname(__FILE__))
require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # Use static frameworks to play nicely with Flutter plugins
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
