platform :ios, '13.0'

# Point to the Flutter SDK installed on the CI runner (or locally)
flutter_root = ENV['FLUTTER_ROOT']
raise "FLUTTER_ROOT not set" if flutter_root.nil? || flutter_root.empty?

require File.expand_path('packages/flutter_tools/bin/podhelper', flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  # static frameworks work best with Flutter plugins
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
